import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.sass"
import React from "react"

import Footer from "@/components/Basic/Footer"
import Header from "@/components/Basic/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
          <Header />
          {children}
          <Footer />
      </body>
    </html>
  );
}
